###
POST http://localhost:3000/posts
Content-Type: application/json

{
    "title": "Hello", 
    "SenderId": "55", 
    "content": "beautiful day"
}
###
GET http://localhost:3000/posts

###
GET http://localhost:3000/posts/674060662936d54632477a58

###
GET http://localhost:3000/posts/?SenderId=55

###
PUT http://localhost:3000/posts/674060662936d54632477a58

Content-Type: application/json

{
    "title": "ThanksDor",
    "SenderId": "55", 
    "content": "beautiful day"
}

###
POST http://localhost:3000/comments
Content-Type: application/json


{
    "postId": "674060662936d54632477a58", 
    "content": "Hello", 
    "username": "natan"
}


###

GET http://localhost:3000/comments



###
PUT http://localhost:3000/comments/674353f402429aaee563dae3
Content-Type: application/json


{
    "postId": "674060662936d54632477a58", 
    "content": "Hi", 
    "username": "ofek"
}


###
DELETE  http://localhost:3000/comments/6743515ea31782524c77a21c

